### ISSUE TITLE
Не удаляется комментарий

### ISSUE THREAD

**Issue by ValeriyMenshikov** [quilin/dm#19]
curl 'http://localhost:5051/v1/forum/comments/Fji07VzYyEi0B1wC7VOaRA' \
  -X 'DELETE' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Cache-Control: no-cache' \
  -H 'x-dm-bb-render-mode: html' \
  -H 'x-dm-auth-token: IQJh+zgzF5CWUDLxan5OYNp2sjB7lPMgj/uWHvtMpWEEQm+gXb9tEnAdfXSoobHwHQ4zkgI+y1LFLQnPpcvxWEJDw8SfsjPHXOLBRb9SqaF8hGC+ZarTOYyg3C+LwWwCQz3G8TOMhVE=' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'Origin: http://localhost:5050' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:5050/' \
  -H 'Accept-Language: ru-RU,ru;q=0.9,en-XA;q=0.8,en;q=0.7,en-US;q=0.6' \
  --compressed

{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"Missing map from DM.Services.DataAccess.BusinessObjects.Common.Like to DM.Services.Core.Dto.GeneralUser. Create using CreateMap<Like, GeneralUser>.","status":500,"detail":"Server error. Address the administration for technical support. Use the following token to help us identify your issue: 3b5f5374-cfa1-435c-b5cf-862f6731343c","traceId":"00-df24c06d92e71547a3504cbb31451555-35d9e8cc563e7d4e-00"}

**Comment by quilin** [comment]
Исправлено в https://github.com/quilin/dm/pull/20
